### ISSUE TITLE
How to restore a dump

### ISSUE THREAD

**Issue by cmonty14** [JGroselle/mariabackup#6]
Could you please include the instructions for restoring a dump in your docu?
This is not trivial if not looking into the script code of mariabackup.

**Comment by JGroselle** [comment]
My script just gzip dump files. So you have two ways to restore:
```bash
gunzip dump.sql.gz
mysql $database < dump.sql
```

Or one liner:

```bash
gunzip < dump.sql.gz | mysql $database
```

This is standard command. It is not part of my script.
